### ISSUE TITLE
Ajus - Modificaciones Tablero | Tablero por Comprador

### ISSUE THREAD

**Issue by lsartoriIA** [InteligenciaAnalitica/MILICIC#174]
![image.png](https://images.zenhubusercontent.com/5d652392a966b62d8f67985c/d0276189-ace7-4567-86cf-bd3a8d2913b0)

**Comment by orcorsettiIA** [comment]
**Pendiente:** Esperar a tener noticias del nuevo jefe

**Comment by orcorsettiIA** [comment]
**Ampliación: ** Consulta hecha 15/12/20
![imagen.png](https://images.zenhubusercontent.com/5f7b4ab43db0814c3a4e5e6a/02abf643-9f22-45e2-b339-1eb340eebd30)

**Comment by orcorsettiIA** [comment]
**Seguimiento: ** Mail enviado el 16/12/2020 - pendiente de confirmación reunión de revisión
