### ISSUE TITLE
Tablero de Control - RRHH (Power BI)

### ISSUE THREAD

**Issue by lsartoriIA** [InteligenciaAnalitica/MILICIC#60]

**Comment by orcorsettiIA** [comment]
**En curso: ** Pagina Dotacion por Gerencia enviada el 28/12/2020

**Comment by orcorsettiIA** [comment]
**Seguimiento: ** Mail con el tablero publicado enviado el 06/01/2021. Cuenta de publicación: milicic@inteligenciaanalitica.com
